### ISSUE TITLE
Respawn Timer does not work with Serpents Hand or UIU Rescue Squad.

### ISSUE THREAD

**Issue by SnivyFilms** [Michal78900/RespawnTimer#18]
Before I start. I want to mention I am using my own version of Respawn Timer that was updated to Exiled 8, but this issue has existed since Exiled 7.

Due to heavy reworks for Exiled 7 Serpents Hand and UIU Rescue Squad updates, API calls from both SH and UIU have changed. Using https://github.com/NikkiGardiner1/SerpentsHand and https://github.com/NikkiGardiner1/UIURescueSquad APIs there should be an update for Respawn Timer that brings back the functionality of saying CI/MTF/SH/UIU respawn instead of CI/MTF

**Comment by funniman-exe** [comment]
What version of respawn timer are you using thats updated to exiled 8? please i need a link as i have been without respawn timer for a good while now and looking for a solution for so long.

And if you have a version of serpents hand that runs on exiled 8, please link too. Thanks.

**Comment by SnivyFilms** [comment]
For Michal78900

https://github.com/Misfiy/RespawnTimer

This version of Respawn Timer is updated to Exiled 8, and it has been also updated to work Serpents Hand and UIU
