### ISSUE TITLE
[SUGGESTION] Respawn timer appear at specific time

### ISSUE THREAD

**Issue by DinoNuggets2** [Michal78900/RespawnTimer#4]
Add a configuration to make the respawn timer only show up when it would be about 20 ish seconds before the respawn, or when it would normally say who is going to spawn (MTF or CI)

**Comment by Oyplap** [comment]
Also looking for this

**Comment by Michal78900** [comment]
Timer is fully configurable, you can either remove the timer part from the file or clear the file entirely. There is no need for creating a config option if you are able to do it yourself already.
